version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi-hello:latest
    container_name: fastapi-hello
    ports:
      - "8000:8000"
    restart: unless-stopped

